language: java

jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master

install: true

script:
  - mvn help:system
  - mvn install -DskipTests=true

